In [1]:
import pandas as pd
import numpy as np

pd.options.display.max_columns = 100
pd.options.display.max_columns = 3000

# Load and Merge Data

In [ ]:
cd ../..

In [29]:
train = pd.read_csv('./datasets/train.csv')
test = pd.read_csv('./datasets/test.csv')

In [34]:
def merge_files(train, test):
    
    # Add source column to train data
    train['source'] = 'train'
    
    #Add Sale price and source to test data
    test['SalePrice'] = 0
    test['source'] = 'test'
    
    # Merge train and test
    final = pd.concat([train, test])
    
    # Update the headings of the final dataset
    new_columns_dict = {c: c.replace(' ', '_').lower() for c in df.columns} #lowercase all column headings
    final.rename(columns = new_columns_dict, inplace = True)
    
    return final

In [3]:
def sep_data(df):
    train = df[df['source'] == 'train']
    train.drop('source', axis=1, inplace=True)
    test = df[df['source'] == 'test']
    test.drop(['source', 'saleprice'], axis=1, inplace=True)

In [4]:
def evaluate_model(model, X, y):
    print(f'R2 Score: {r2_score(y, model.predict(X))}')
    print(f'MSE: {mean_squared_error(y, model.predict(X))}')
    print(f'RMSE: {np.sqrt(mean_squared_error(y, model.predict(X)))}')

In [ ]:
def scale_model(X, y):

In [5]:
def linear_model(X_train, y_train):
    lr = LinearRegression()
    lr.fit(X_train, y_train)

In [6]:
def add_dummies(df, dummy_list):
    df = pd.get_dummies(columns=dummy_list, drop_first=True, data=df) #drop_first=True, drops the first column

In [7]:
def save_output(testset, output_file):
    pred_price = lr.predict(testset)
    test['y_hat'] = lr.predict(testset)
    submission = pd.DataFrame({'id': test['id'],
                            'SalePrice': test['y_hat']})
    submission.to_csv(output_file, index = False)

In [33]:
train

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice,source
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2010,WD,130500,train
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,4,2009,WD,220000,train
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,1,2010,WD,109000,train
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,174000,train
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2010,WD,138500,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2046,1587,921126030,20,RL,79.0,11449,Pave,NaN,IR1,HLS,...,0,NaN,NaN,NaN,0,1,2008,WD,298751,train
2047,785,905377130,30,RL,NaN,12342,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2009,WD,82500,train
2048,916,909253010,50,RL,57.0,7558,Pave,NaN,Reg,Bnk,...,0,NaN,NaN,NaN,0,3,2009,WD,177000,train
2049,639,535179160,20,RL,80.0,10400,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2009,WD,144000,train
2050,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,189000,train

In [35]:
df = merge_files(train, test)
df

AttributeError: 'NoneType' object has no attribute 'columns'

In [22]:
load_and_merge()

FileNotFoundError: [Errno 2] File ../datasets/train.csv does not exist: '../datasets/train.csv'

In [8]:
plt.figure(figsize=(15, 10))

sns.heatmap(df.corr()[['saleprice']].sort_values('saleprice'),
            annot=True,
            vmin=-1,
            vmax=1,
            cmap='coolwarm');

NameError: name 'plt' is not defined

In [ ]:
sns.pairplot(df, y_vars=['saleprice'], x_vars=["lot_area", "street", "lot_shape", "yr_sold", "condition_1", "neighborhood"]);